# Basic Python

## 1. Split this string

In [93]:
s = "Hi there Sam!"

In [94]:
s.split()
print(s)

Hi there Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [95]:
planet = "Earth"
diameter = 12742

In [124]:
txt= "The diameter of {} is {} kilometers."
print(txt.format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [125]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [127]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [128]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [129]:

import numpy as np
array1= np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [130]:
import numpy as np
array2=np.ones(10)*5
print(array2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [131]:

import numpy as np
array =np.arange(20,35,2)
print("-----Even array Integers form 20 - 35-----")
print(array)

-----Even array Integers form 20 - 35-----
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [132]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [133]:
import numpy as np
a=np.array([1,2,3])
b= np.array([4,5,6])
print("---concatenated Array---")
np.concatenate((a,b))

---concatenated Array---


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [134]:
import pandas as pd


In [135]:
lists = [[1, 'Apple'], [2, 'Orange'], [3, 'Grapes']]
df= pd.DataFrame(lists)

df

0       1
0  1   Apple
1  2  Orange
2  3  Grapes

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [136]:
import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-1-2022", "%d-%m-%Y")
 
# initializing K
K = 59
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2022', '02-01-2022', '03-01-2022', '04-01-2022', '05-01-2022',
       '06-01-2022', '07-01-2022', '08-01-2022', '09-01-2022', '10-01-2022',
       '11-01-2022', '12-01-2022', '13-01-2022', '14-01-2022', '15-01-2022',
       '16-01-2022', '17-01-2022', '18-01-2022', '19-01-2022', '20-01-2022',
       '21-01-2022', '22-01-2022', '23-01-2022', '24-01-2022', '25-01-2022',
       '26-01-2022', '27-01-2022', '28-01-2022', '29-01-2022', '30-01-2022',
       '31-01-2022', '01-02-2022', '02-02-2022', '03-02-2022', '04-02-2022',
       '05-02-2022', '06-02-2022', '07-02-2022', '08-02-2022', '09-02-2022',
       '10-02-2022', '11-02-2022', '12-02-2022', '13-02-2022', '14-02-2022',
       '15-02-2022', '16-02-2022', '17-02-2022', '18-02-2022', '19-02-2022',
       '20-02-2022', '21-02-2022', '22-02-2022', '23-02-2022', '24-02-2022',
       '25-02-2022', '26-02-2022', '27-02-2022', '28-02-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [137]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [138]:


for b in lists:
    for j in b:
        print(j)

dt=zip(lists)
df=pd.DataFrame(dt,columns=["dataFrame"])
print(df)

1
aaa
22
2
bbb
25
3
ccc
24
      dataFrame
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
